### ISSUE TITLE
TypeError: Cannot read property 'toggle' of null

### ISSUE THREAD

**Issue by pajasry** [Gromina/node-red-contrib-yeelight#8]
hi,
i am using node red on RPI3 with this code.
And i getting error `TypeError: Cannot read property 'toggle' of null`
Do you know how to fix it?

`[{"id":"bbc5af13.b3c0a","type":"tab","label":"Xiaomi_Bulb","disabled":false,"info":""},{"id":"28beafdb.65d4d8","type":"yeelight","z":"bbc5af13.b3c0a","name":"Set RGB Color","command":"set_rgb","config":"","x":670,"y":160,"wires":[[]]},{"id":"2abb2e52.f22342","type":"ui_colour_picker","z":"bbc5af13.b3c0a","name":"Color Picker","label":"COLOR PICKER","group":"2d9d8665.6f161a","format":"hex","outformat":"string","showSwatch":true,"showPicker":true,"showValue":true,"showAlpha":true,"showLightness":true,"order":1,"width":0,"height":0,"passthru":true,"topic":"","x":308,"y":161,"wires":[["f33dc6b9.1eff5"]]},{"id":"f33dc6b9.1eff5","type":"function","z":"bbc5af13.b3c0a","name":"Format Color","func":"msg.payload = msg.payload.replace(/[#]/g,\"0x\");\nreturn msg;\n","outputs":1,"noerr":0,"x":466,"y":161,"wires":[["28beafdb.65d4d8"]]},{"id":"937a9e44.d08508","type":"yeelight","z":"bbc5af13.b3c0a","name":"Set Temperature","command":"set_ct_abx","config":"","x":614,"y":252,"wires":[[]]},{"id":"ff5c47c0.c7645","type":"yeelight","z":"bbc5af13.b3c0a","name":"Toggle","command":"toggle","config":"","x":580,"y":340,"wires":[[]]},{"id":"49994e35.23055","type":"ui_button","z":"bbc5af13.b3c0a","name":"Toggle","group":"2d9d8665.6f161a","order":5,"width":0,"height":0,"passthru":false,"label":"TOGGLE","tooltip":"","color":"","bgcolor":"","icon":"","payload":"true","payloadType":"bool","topic":"","x":289,"y":345,"wires":[["ff5c47c0.c7645"]]},{"id":"e7c75989.46ff18","type":"ui_slider","z":"bbc5af13.b3c0a","name":"Set Temperature","label":"SET TEMPERATURE","tooltip":"","group":"2d9d8665.6f161a","order":3,"width":0,"height":0,"passthru":true,"outs":"all","topic":"","min":"1700","max":"6500","step":"10","x":328,"y":252,"wires":[["937a9e44.d08508"]]},{"id":"95a12d50.90174","type":"ui_slider","z":"bbc5af13.b3c0a","name":"Set Brightness","label":"SET BRIGHTNESS","tooltip":"","group":"2d9d8665.6f161a","order":2,"width":0,"height":0,"passthru":true,"outs":"all","topic":"","min":"1","max":"100","step":1,"x":319,"y":209,"wires":[["6c174db6.ef71f4"]]},{"id":"6c174db6.ef71f4","type":"yeelight","z":"bbc5af13.b3c0a","name":"Set Brightness","command":"set_bright","config":"","x":605,"y":209,"wires":[[]]},{"id":"d0f680e.01adb","type":"yeelight","z":"bbc5af13.b3c0a","name":"Set RGB Color","command":"set_rgb","config":"","x":614,"y":297,"wires":[[]]},{"id":"88663de6.d20ad8","type":"ui_dropdown","z":"bbc5af13.b3c0a","name":"Select Color","label":"SELECT COLOR","tooltip":"","place":"CHOOSE","group":"2d9d8665.6f161a","order":4,"width":0,"height":0,"passthru":true,"options":[{"label":"RED","value":"0xFF0000","type":"str"},{"label":"GREEN","value":"0x00FF00","type":"str"},{"label":"BLUE","value":"0x0000FF","type":"str"},{"label":"WHITE","value":"0xFFFFFF","type":"str"},{"label":"CYAN","value":"0x00FFFF","type":"str"},{"label":"PURPLE","value":"0xFF00FF","type":"str"},{"label":"YELLOW","value":"0xFFFF00","type":"str"}],"payload":"","topic":"","x":310,"y":297,"wires":[["d0f680e.01adb"]]},{"id":"2d9d8665.6f161a","type":"ui_group","z":"","name":"Yeelight Smart Bulb","tab":"5a415962.4a9628","order":1,"disp":true,"width":"6"},{"id":"5a415962.4a9628","type":"ui_tab","z":"","name":"Office","icon":"dashboard","order":1}]`

**Comment by m4dm4n** [comment]
I confirm the same problem.

**Comment by PTS93** [comment]
Had the same issue, the fix is simple. I made a pull request here: https://github.com/Gromina/node-red-contrib-yeelight/pull/9
